// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: refresh_tokens.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const assignRefreshTokenToUser = `-- name: AssignRefreshTokenToUser :one
INSERT INTO refresh_tokens (token, created_at, updated_at, user_id, expires_at, revoked_at)
VALUES (
  $1,
  NOW(),
  NOW(),
  $2,
  NOW() + INTERVAL '60 days',
  NULL
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type AssignRefreshTokenToUserParams struct {
	Token  string
	UserID uuid.NullUUID
}

func (q *Queries) AssignRefreshTokenToUser(ctx context.Context, arg AssignRefreshTokenToUserParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, assignRefreshTokenToUser, arg.Token, arg.UserID)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
