### Get Request
GET http://localhost:8080/app

### Get Request
GET http://localhost:8080/admin

### Get Request
GET http://localhost:8080/api/healthz

### Get Request
GET http://localhost:8080/api/metrics

### Post Request
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "tatia@example.com"
}

### Post Request
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
    "body": "Hello, world!",
    "user_id": "17fe2a4e-f643-45f5-9108-b3a480a2dd4d"  
}

### Post Request
POST http://localhost:8080/admin/resetUsers

### Post Request
POST http://localhost:8080/admin/resetChirps

### Post Request
POST http://localhost:8080/admin/resetHits

### Post Request
POST http://localhost:8080/admin/reset

### Post Request
POST http://localhost:8080/admin
