### Get Request
GET http://localhost:8080/app

### Get Request
GET http://localhost:8080/admin

### Get Request
GET http://localhost:8080/api/healthz

### Get Request
GET http://localhost:8080/api/metrics

### Get Request
GET http://localhost:8080/api/users

### Get Request
GET http://localhost:8080/api/chirps

### Post Request
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "somepassword"
}

### Post Request
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "email": "newuser@example.com",
  "password": "somepassword",
  "expires_in_seconds": 5000
}

### Post Request
POST http://localhost:8080/api/chirps
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJkYTM4ZTYyNy03YjE4LTRiNzktOWUzMS1lMzNlYjI3ZWVmNzMiLCJleHAiOjE3MjgzNzEyMTgsImlhdCI6MTcyODM2NzYxOH0.nprZdEWw6VmXWG-D6QHx7ngEEY9cdMqXLFY4g-vpR08

{
    "body": "chirp chirp"
}

### Get Request
GET http://localhost:8080/api/chirps/3753c263-160a-4856-be01-072c6a3c3abe


### Post Request
POST http://localhost:8080/admin/resetUsers

### Post Request
POST http://localhost:8080/admin/resetChirps

### Post Request
POST http://localhost:8080/admin/resetHits

### Post Request
POST http://localhost:8080/admin/reset

### Post Request
POST http://localhost:8080/admin
